import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { NexusOAuth } from '../src/oauth.mjs';
import { NexusService } from '../src/nexus-service.mjs';
import { MemoryRepository, config } from './fixture.mjs';
import { linked } from './oauth-fixture.mjs';

test('ChatGPT and Claude follow per-user OAuth with PKCE and state', async () => { for (const provider of ['Claude', 'ChatGPT']) { const { oauth, tokens, callback } = await linked({ provider }); assert.equal(callback.searchParams.get('state'), 'state-fixture'); assert.equal((await oauth.authenticate(tokens.access_token)).uid, 'alice'); } });
test('authorization codes and consent tickets cannot be replayed', async () => { const { oauth, exchange, ticket } = await linked(); await assert.rejects(oauth.token(exchange), { code: 'invalid_grant' }); await assert.rejects(oauth.approve(ticket, 'alice', ['owner'], true), { code: 'request_expired' }); });
test('read-only consent cannot be elevated by refresh or tool use', async () => { const { oauth, tokens, service, client } = await linked({ write: false }); const actor = await oauth.authenticate(tokens.access_token); assert.deepEqual(actor.scopes, ['tasks:read']); await assert.rejects(service.createTask(actor, 'owner', 'maintenance', { requerimiento: 'Nueva', rubro: 'General' }, 'request-1234567890'), { code: 'insufficient_scope' }); await assert.rejects(oauth.token({ client_id: client.client_id, grant_type: 'refresh_token', refresh_token: tokens.refresh_token, resource: `${config.baseUrl}/mcp`, scope: 'tasks:read tasks:write' }), { code: 'invalid_scope' }); });
test('refresh rotates tokens; revoked connection invalidates both token types', async () => { const { oauth, tokens, client } = await linked(); const input = { client_id: client.client_id, grant_type: 'refresh_token', refresh_token: tokens.refresh_token, resource: `${config.baseUrl}/mcp` }; const fresh = await oauth.token(input); await assert.rejects(oauth.token(input), { code: 'invalid_grant' }); await oauth.revokeToken({ token: fresh.refresh_token, client_id: client.client_id }); await assert.rejects(oauth.authenticate(tokens.access_token), { code: 'invalid_token' }); await assert.rejects(oauth.authenticate(fresh.access_token), { code: 'invalid_token' }); });
test('tokens are hashed at rest and another user cannot revoke the connection', async () => { const { oauth, tokens, repo } = await linked(); assert.ok(!JSON.stringify([...repo.documents]).includes(tokens.access_token)); assert.ok(!JSON.stringify([...repo.documents]).includes(tokens.refresh_token)); const actor = await oauth.authenticate(tokens.access_token); await assert.rejects(oauth.revokeGrant('bob', actor.grantId), { code: 'grant_not_found' }); });
test('malicious redirects, missing PKCE, and wrong resource are rejected', async () => { const { oauth, client, exchange } = await linked(); for (const redirect of ['https://attacker.example/callback', 'https://claude.ai.attacker.example/api/mcp/auth_callback', 'https://claude.ai/api/mcp/auth_callback?redirect=evil', 'http://claude.ai/api/mcp/auth_callback']) await assert.rejects(oauth.register({ redirect_uris: [redirect] }), { code: 'invalid_redirect_uri' }); await assert.rejects(oauth.begin({ client_id: client.client_id, redirect_uri: exchange.redirect_uri, response_type: 'code', resource: `${config.baseUrl}/mcp`, state: 'fixture' }), { code: 'invalid_request' }); await assert.rejects(oauth.token({ ...exchange, resource: 'https://attacker.example/mcp' }), { code: 'invalid_target' }); });
test('wrong PKCE verifier does not consume a valid code', async () => { const repo = new MemoryRepository(), service = new NexusService(repo, config.webUrl), oauth = new NexusOAuth(repo, service, config); const redirect = 'https://claude.ai/api/mcp/auth_callback'; const client = await oauth.register({ redirect_uris: [redirect] }); const verifier = 'b'.repeat(64); const url = await oauth.begin({ client_id: client.client_id, redirect_uri: redirect, response_type: 'code', code_challenge: createHash('sha256').update(verifier).digest('base64url'), code_challenge_method: 'S256', resource: `${config.baseUrl}/mcp`, state: 'fixture' }); const ticket = url.split('request=')[1]; const approval = await oauth.approve(ticket, 'alice', ['owner'], false); const code = new URL(approval.redirectUrl).searchParams.get('code'); const input = { client_id: client.client_id, redirect_uri: redirect, grant_type: 'authorization_code', code, resource: `${config.baseUrl}/mcp` }; await assert.rejects(oauth.token({ ...input, code_verifier: 'c'.repeat(64) }), { code: 'invalid_grant' }); assert.ok((await oauth.token({ ...input, code_verifier: verifier })).access_token); });
