import test from 'node:test';
import assert from 'node:assert/strict';
import { NexusService } from '../src/nexus-service.mjs';
import { MemoryRepository, config, grant } from './fixture.mjs';
import { parse, createTaskSchema } from '../src/validation.mjs';
const setup = async () => { const repo = new MemoryRepository(); return { repo, service: new NexusService(repo, config.webUrl), actor: await grant(repo) }; };
test('scopes limit accessible workspaces even when the user owns more', async () => { const { service, actor } = await setup(); assert.deepEqual((await service.listWorkspaces(actor)).workspaces.map(w => w.id), ['owner']); await assert.rejects(service.projects(actor, 'alice'), { code: 'workspace_not_authorized' }); });
test('admins can create in delegated workspace; unrelated workspaces and forged project IDs fail', async () => { const { service, actor } = await setup(); await assert.rejects(service.projects(actor, 'bob'), { status: 403 }); await assert.rejects(service.tasks(actor, 'owner', 'bobproject'), { status: 404 }); });
test('revoking membership immediately removes read/write access', async () => { const { repo, service, actor } = await setup(); delete repo.data.admin_map['alice@example,com'].owner; await assert.rejects(service.tasks(actor, 'owner', 'maintenance'), { code: 'access_denied' }); await assert.rejects(service.createTask(actor, 'owner', 'maintenance', { requerimiento: 'Nueva', rubro: 'General' }, 'request-1234567890'), { status: 403 }); });
test('stale or false admin index alone cannot grant access', async () => { const { repo, service } = await setup(); repo.data.admin_map['alice@example,com'].owner = false; assert.equal((await service.workspaces('alice')).length, 1); repo.data.admin_map['alice@example,com'].owner = true; delete repo.data.users.owner.config.admins['alice@example,com']; assert.equal((await service.workspaces('alice')).length, 1); });
test('historical membership does not hide other currently authorized spaces', async () => { const { repo, service } = await setup(); repo.data.admin_map['alice@example,com'].ownerId = 'legacy'; repo.data.users.legacy = { authorized_admins: { 'alice@example,com': true } }; assert.deepEqual((await service.workspaces('alice')).map(space => space.id), ['alice', 'legacy', 'owner']); delete repo.data.users.legacy.authorized_admins['alice@example,com']; assert.deepEqual((await service.workspaces('alice')).map(space => space.id), ['alice', 'owner']); });
test('read-only connection rejects writes', async () => { const { repo, service } = await setup(); const actor = await grant(repo, { scopes: ['tasks:read'] }); await assert.rejects(service.createTask(actor, 'owner', 'maintenance', { requerimiento: 'Nueva', rubro: 'General' }, 'request-1234567890'), { code: 'insufficient_scope' }); });
test('grant revocation and disabled accounts reject operations', async () => { const { repo, service, actor } = await setup(); const g = await repo.privateGet('grants', actor.grantId); await repo.privatePut('grants', actor.grantId, { ...g, revokedAt: Date.now() }); await assert.rejects(service.listWorkspaces(actor), { status: 401 }); repo.users.get('alice').disabled = true; await assert.rejects(service.workspaces('alice'), { status: 403 }); });
test('retries create exactly one task and one audit record', async () => { const { repo, service, actor } = await setup(); const input = { requerimiento: 'Pedir presupuesto', rubro: 'Seguridad', responsable: 'Pablo', deadline: '2026-10-09' }; const first = await service.createTask(actor, 'owner', 'maintenance', input, 'request-1234567890'); const second = await service.createTask(actor, 'owner', 'maintenance', input, 'request-1234567890'); assert.deepEqual(first, second); assert.equal(Object.keys(repo.data.project_data.maintenance.tasks).length, 2); assert.equal((await repo.privateList('audit', 'alice')).length, 1); await assert.rejects(service.createTask(actor, 'owner', 'maintenance', { ...input, requerimiento: 'Otro' }, 'request-1234567890'), { code: 'request_id_reused' }); });
test('recovering from failed audit write does not duplicate task', async () => { const { repo, service, actor } = await setup(); const put = repo.privatePut.bind(repo); let fail = true; repo.privatePut = async (collection, id, data) => { if (collection === 'audit' && fail) { fail = false; throw new Error('Temporary failure'); } return put(collection, id, data); }; const input = { requerimiento: 'Prueba', rubro: 'General' }; await assert.rejects(service.createTask(actor, 'owner', 'maintenance', input, 'request-1234567890')); const result = await service.createTask(actor, 'owner', 'maintenance', input, 'request-1234567890'); assert.equal(result.saved, true); assert.equal(Object.keys(repo.data.project_data.maintenance.tasks).length, 2); });
test('edits preserve attachments/comments and reject concurrent changes', async () => { const { repo, service, actor } = await setup(); const before = await service.task(actor, 'owner', 'maintenance', 'existing'); const result = await service.updateTask(actor, 'owner', 'maintenance', 'existing', { prioridad: 'Alta' }, before.version, 'request-1234567890'); assert.equal(result.task.prioridad, 'Alta'); assert.equal(repo.data.project_data.maintenance.tasks.existing.attachments[0].content, 'PRIVATE-BINARY'); assert.equal(repo.data.project_data.maintenance.tasks.existing.comments[0].text, 'Conservar'); await assert.rejects(service.updateTask(actor, 'owner', 'maintenance', 'existing', { prioridad: 'Baja' }, before.version, 'different-request-123'), { code: 'version_conflict' }); });
test('outputs exclude sharing tokens and binary attachments; pagination is explicit', async () => { const { service, actor } = await setup(); const details = await service.details(actor, 'owner', 'maintenance'); const first = await service.tasks(actor, 'owner', 'maintenance', { limit: 1 }); assert.ok(!JSON.stringify({ details, first }).includes('NEVER-RETURN-THIS')); assert.ok(!JSON.stringify(first).includes('PRIVATE-BINARY')); assert.equal(first.nextCursor, null); await service.createTask(actor, 'owner', 'maintenance', { requerimiento: 'Otra', rubro: 'General' }, 'request-1234567890'); const page = await service.tasks(actor, 'owner', 'maintenance', { limit: 1 }); assert.ok(page.nextCursor); assert.equal((await service.tasks(actor, 'owner', 'maintenance', { cursor: page.nextCursor })).tasks.length, 1); });
test('unknown labels, metadata injection, invalid dates and HTML are rejected', async () => { const { service, actor } = await setup(); for (const input of [{ requerimiento: 'Nueva', rubro: 'Inventado' }, { requerimiento: 'Nueva', rubro: 'General', responsable: 'Inventado' }, { requerimiento: 'Nueva', rubro: 'General', owner: 'bob' }, { requerimiento: 'Nueva', rubro: 'General', deadline: '2026-02-30' }, { requerimiento: '<img onerror=alert(1)>', rubro: 'General' }]) await assert.rejects(service.createTask(actor, 'owner', 'maintenance', input, 'request-1234567890'), { status: 400 }); assert.throws(() => parse(createTaskSchema, { requerimiento: 'Nueva', rubro: 'General', deadline: 'bad-date' })); });
test('archived writes and incomplete legacy recurrence fail without changing data', async () => { const { repo, service, actor } = await setup(); await assert.rejects(service.createTask(actor, 'owner', 'archived', { requerimiento: 'Nueva', rubro: 'General' }, 'request-1234567890'), { code: 'archived_project' }); repo.data.project_data.maintenance.tasks.existing.recurrence = { type: 'weekly' }; const task = await service.task(actor, 'owner', 'maintenance', 'existing'); await assert.rejects(service.updateTask(actor, 'owner', 'maintenance', 'existing', { estado: 'Realizado' }, task.version, 'request-1234567890'), { code: 'invalid_recurrence' }); assert.equal(repo.data.project_data.maintenance.tasks.existing.estado, 'Pendiente'); });

test('reserved rubros cannot hide a task through ordinary creation or editing', async () => {
  const { repo, service, actor } = await setup();
  repo.data.project_data.maintenance.rubros.push('Eliminado', 'Realizados');
  const before = await service.task(actor, 'owner', 'maintenance', 'existing');
  for (const rubro of ['Eliminado', 'Realizados']) {
    await assert.rejects(service.createTask(actor, 'owner', 'maintenance', { requerimiento: 'Nueva', rubro }, 'request-1234567890'), { code: 'unknown_rubro' });
    await assert.rejects(service.updateTask(actor, 'owner', 'maintenance', 'existing', { rubro }, before.version, 'request-1234567890'), { code: 'unknown_rubro' });
  }
  assert.equal(repo.data.project_data.maintenance.tasks.existing.rubro, 'Seguridad');
});

test('simultaneous edits with the same version allow only one writer', async () => {
  const { service, actor } = await setup();
  const before = await service.task(actor, 'owner', 'maintenance', 'existing');
  const results = await Promise.allSettled([
    service.updateTask(actor, 'owner', 'maintenance', 'existing', { prioridad: 'Alta' }, before.version, 'parallel-request-one'),
    service.updateTask(actor, 'owner', 'maintenance', 'existing', { prioridad: 'Baja' }, before.version, 'parallel-request-two')
  ]);
  assert.equal(results.filter(result => result.status === 'fulfilled').length, 1);
  assert.equal(results.find(result => result.status === 'rejected').reason.code, 'version_conflict');
});
